# Website Metadata
# Website Metadata
title: Xiurou Wu
baseurl: 'https://xiurouwu.github.io/'
copyright: '© {2021} Xiurou Wu'
googleAnalytics: 'G-F341NY68GJ'  # Move it here, at the top level

############################
## PARAMETERS
############################

# Remove googleAnalytics completely from the params section



############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

############################
## ADVANCED SETTINGS
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

############################
## SECURITY SETTINGS
############################

security:
  enableInlineShortcodes: false
  exec:
    allow:
      - '^(dart-)?sass(-embedded)?$'
      - '^go$'
      - '^git$'
      - '^npx$'
      - '^postcss$'
      - '^tailwindcss$'
    osEnv:
      - '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$'
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^WC_POST_CSS$'
  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']
